[package]
name = "godot-naga"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"
license = "MIT"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
naga = { path = "vendor/naga", features = ["glsl-in", "msl-out", "spv-in", "spv-out"] }
spirv = "0.4.0"

[profile.release]
panic = "unwind"
lto = "thin"
