#!/usr/bin/env node
/**
 * test_wgsl_cache.mjs — Unit tests for the build-time WGSL precompilation system.
 *
 * Tests:
 * 1. Generated header C++ syntax validation
 * 2. Precompiled table binary search contract
 *
 * These tests validate the generated header format without requiring
 * a full engine build or the Tint CLI tool.
 *
 * Usage:
 *   node test_wgsl_cache.mjs
 */

import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const GEN_HEADER = join(REPO_ROOT, 'drivers', 'webgpu', 'wgsl_precompiled.gen.h');

let passed = 0;
let failed = 0;

function assert(cond, msg) {
	if (!cond) {
		console.error(`  FAIL: ${msg}`);
		failed++;
	} else {
		console.log(`  PASS: ${msg}`);
		passed++;
	}
}


// =========================================================================
// Test 1: Generated header format validation
// =========================================================================
console.log('\n=== Test 1: Generated header validation ===');

if (existsSync(GEN_HEADER)) {
	const content = readFileSync(GEN_HEADER, 'utf-8');

	assert(content.includes('// Auto-generated by'),
		'Header has auto-generated comment');
	assert(content.includes('#pragma once'), 'Header has include guard');
	assert(content.includes('#include <cstdint>'), 'Header includes cstdint');
	assert(content.includes('struct WgslPrecompiledEntry'), 'Header has struct definition');
	assert(content.includes('_wgsl_precompiled_count'), 'Header has count variable');

	// Extract count.
	const countMatch = content.match(/_wgsl_precompiled_count\s*=\s*(\d+)/);
	assert(countMatch !== null, 'Count variable has numeric value');
	const count = parseInt(countMatch?.[1] ?? '0');

	if (count > 0) {
		// Verify hashes are sorted (critical for binary search).
		const hashRegex = /0x([0-9A-Fa-f]+)ULL/g;
		const hashes = [];
		let match;
		while ((match = hashRegex.exec(content)) !== null) {
			hashes.push(BigInt('0x' + match[1]));
		}
		assert(hashes.length === count, `Found ${hashes.length} hashes matching count ${count}`);

		let sorted = true;
		for (let i = 1; i < hashes.length; i++) {
			if (hashes[i] <= hashes[i - 1]) {
				sorted = false;
				break;
			}
		}
		assert(sorted, 'All hashes are strictly sorted (ascending)');

		// Verify raw string literal syntax.
		const rawStringCount = (content.match(/R"wgsl\(/g) || []).length;
		assert(rawStringCount === count, `Found ${rawStringCount} raw string literals matching count ${count}`);
	} else {
		console.log('  INFO: Header has 0 precompiled entries (Tint CLI not available during build).');
		console.log('        This is expected — runtime Tint handles all conversion.');
	}
} else {
	console.log('  SKIP: wgsl_precompiled.gen.h not found (run scons build first)');
}


// =========================================================================
// Test 2: Binary search contract simulation
// =========================================================================
console.log('\n=== Test 2: Binary search contract ===');

{
	// Simulate the C++ binary search on the sorted hash array.
	function binarySearch(entries, target) {
		let lo = 0, hi = entries.length;
		while (lo < hi) {
			const mid = lo + ((hi - lo) >> 1);
			if (entries[mid].hash < target) lo = mid + 1;
			else if (entries[mid].hash > target) hi = mid;
			else return entries[mid].wgsl;
		}
		return null;
	}

	// Test with known entries.
	const testEntries = [
		{ hash: 1n, wgsl: 'fn a() {}' },
		{ hash: 100n, wgsl: 'fn b() {}' },
		{ hash: 1000n, wgsl: 'fn c() {}' },
		{ hash: 10000n, wgsl: 'fn d() {}' },
		{ hash: 100000n, wgsl: 'fn e() {}' },
	];

	assert(binarySearch(testEntries, 1n) === 'fn a() {}', 'Binary search: find first entry');
	assert(binarySearch(testEntries, 100000n) === 'fn e() {}', 'Binary search: find last entry');
	assert(binarySearch(testEntries, 1000n) === 'fn c() {}', 'Binary search: find middle entry');
	assert(binarySearch(testEntries, 42n) === null, 'Binary search: miss returns null');
	assert(binarySearch(testEntries, 0n) === null, 'Binary search: below range returns null');
	assert(binarySearch(testEntries, 999999n) === null, 'Binary search: above range returns null');
	assert(binarySearch([], 42n) === null, 'Binary search: empty table returns null');

	// Stress test: random lookups on large sorted array.
	const large = [];
	for (let i = 0; i < 500; i++) {
		large.push({ hash: BigInt(i * 7 + 3), wgsl: `fn f${i}() {}` });
	}
	assert(binarySearch(large, 3n) === 'fn f0() {}', 'Binary search stress: first element');
	assert(binarySearch(large, BigInt(499 * 7 + 3)) === 'fn f499() {}', 'Binary search stress: last element');
	assert(binarySearch(large, BigInt(250 * 7 + 3)) === 'fn f250() {}', 'Binary search stress: middle element');
	assert(binarySearch(large, 1n) === null, 'Binary search stress: gap miss');
}


// =========================================================================
// Summary
// =========================================================================
console.log(`\n${'='.repeat(50)}`);
console.log(`Results: ${passed} passed, ${failed} failed`);
if (failed > 0) {
	process.exit(1);
}
