name: 🍎 macOS Builds
on:
  workflow_call:
  workflow_dispatch:

# Global Settings
env:
  SCONS_FLAGS: >-
    dev_mode=yes
    module_text_server_fb_enabled=yes
    tests=no
    debug_symbols=no
    library_type=shared_library
    vulkan=no
    metal=yes
    disable_path_overrides=no

jobs:
  macos-libgodot:
    # From https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job#choosing-github-hosted-runners
    runs-on: macos-latest
    name: libgodot macOS (template_debug)
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # From https://github.com/actions/runner-images/blob/main/images/macos
      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.0.1.app

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: macos-libgodot
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation (x86_64)
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} arch=x86_64
          platform: macos
          target: template_debug

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} arch=arm64
          platform: macos
          target: template_debug

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: macos-libgodot
        continue-on-error: true

      - name: Prepare artifact
        run: |
          lipo -create ./bin/libgodot.macos.template_debug.x86_64.dylib ./bin/libgodot.macos.template_debug.arm64.dylib -output ./bin/libgodot.macos.template_debug.universal.dylib
          chmod +x ./bin/libgodot.macos.template_debug.universal.dylib

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: libgodot-macos
          path: |
            bin/libgodot.macos.template_debug.arm64.dylib
            bin/libgodot.macos.template_debug.x86_64.dylib
            bin/libgodot.macos.template_debug.universal.dylib
            core/extension/libgodot.h
            core/extension/gdextension_interface.gen.h
